include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_fields: true
    unnecessary_new: true
    unnecessary_const: true
    prefer_single_quotes: true
    #use_build_context_synchronously: false
