name: numerocide
description: "A game with numbers"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.9
  cupertino_icons: ^1.0.8
  vibration: ^1.7.3
  audioplayers: ^1.0.1
  volume_control: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/add_rows.mp3
    - assets/sounds/gameover-lose.mp3
    - assets/sounds/no_hints.mp3
    - assets/sounds/remove_numbers.mp3
    - assets/sounds/remove_row.mp3
    - assets/sounds/gameover-victory.flac
    - assets/sounds/desk_cleared.wav
    - assets/sounds/hint.wav
    - assets/sounds/tap.aiff
    - assets/pic/example.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon3.png"
