name: numerocide
description: "A game with numbers"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.0.9
  cupertino_icons: ^1.0.8
  vibration: ^2.0.1
  audioplayers: ^6.1.0
  volume_control: ^0.1.5
  in_app_purchase: ^3.0.0
  url_launcher: ^6.0.9
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  mocktail: ^0.2.0
  url_launcher_platform_interface: ^2.0.4

flutter:
  generate: true
  uses-material-design: true
#  gen-l10n:
#    arb-dir: lib/l10n
#  localization:
#      arb-dir: assets/l10n
#      template-arb-file: app_en.arb
#      output-localization-file: l10n.dart
  assets:
    - assets/sounds/add_rows.mp3
    - assets/sounds/gameover-lose.mp3
    - assets/sounds/no_hints.mp3
    - assets/sounds/remove_numbers.mp3
    - assets/sounds/remove_row.mp3
    - assets/sounds/gameover-victory.flac
    - assets/sounds/desk_cleared.wav
    - assets/sounds/hint.wav
    - assets/sounds/tap.aiff
    - assets/pic/example.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_gen_l10n:
  assets:
    - assets/l10n/

#localization:
#    arb-dir: assets/l10n
#    template-arb-file: app_en.arb
#    output-localization-file: l10n.dart
